/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/upload-and-process": {
    /**
     * Upload And Process Scorecard
     * @description Upload scorecard image and process it with Claude API
     *
     * Flow:
     * 1. Receive image from frontend
     * 2. Upload to S3
     * 3. Send to Claude for data extraction
     * 4. Calculate totals and winner
     * 5. Return structured data
     */
    post: operations["upload_and_process_scorecard_api_upload_and_process_post"];
  };
  "/api/export": {
    /**
     * Export Scorecard
     * @description Export scorecard data to CSV or Excel
     *
     * Args:
     *     request: Scorecard data and format (csv or excel)
     *
     * Returns:
     *     File download
     */
    post: operations["export_scorecard_api_export_post"];
  };
  "/": {
    /** Read Root */
    get: operations["read_root__get"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_upload_and_process_scorecard_api_upload_and_process_post */
    Body_upload_and_process_scorecard_api_upload_and_process_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /**
     * ExportRequest
     * @description Request to export scorecard data
     */
    ExportRequest: {
      data: components["schemas"]["ScorecardData"];
      /** Format */
      format: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Player
     * @description Player data with scores
     */
    Player: {
      /** Name */
      name: string;
      /** Scores */
      scores: (number | null)[];
      /** Total */
      total?: number | null;
      /** Front Nine Total */
      front_nine_total?: number | null;
      /** Back Nine Total */
      back_nine_total?: number | null;
    };
    /**
     * ProcessScorecardResponse
     * @description Response after processing scorecard
     */
    ProcessScorecardResponse: {
      /** Scorecard Id */
      scorecard_id: string;
      data: components["schemas"]["ScorecardData"];
      /** Winner */
      winner?: string | null;
      /** Processing Time Ms */
      processing_time_ms: number;
    };
    /**
     * ScorecardData
     * @description Complete scorecard data
     */
    ScorecardData: {
      /** Course */
      course?: string | null;
      /** Date */
      date?: string | null;
      /** Par */
      par?: ((number | null)[]) | null;
      /** Players */
      players: components["schemas"]["Player"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Upload And Process Scorecard
   * @description Upload scorecard image and process it with Claude API
   *
   * Flow:
   * 1. Receive image from frontend
   * 2. Upload to S3
   * 3. Send to Claude for data extraction
   * 4. Calculate totals and winner
   * 5. Return structured data
   */
  upload_and_process_scorecard_api_upload_and_process_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_and_process_scorecard_api_upload_and_process_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessScorecardResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Export Scorecard
   * @description Export scorecard data to CSV or Excel
   *
   * Args:
   *     request: Scorecard data and format (csv or excel)
   *
   * Returns:
   *     File download
   */
  export_scorecard_api_export_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Read Root */
  read_root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
